// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace ProjekatBackend.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20220316225119_V3")]
    partial class V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Auto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AutomobilDostupan")
                        .HasColumnType("bit");

                    b.Property<int>("CenaIznajmljivanja")
                        .HasColumnType("int");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraza")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkaAuta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistarskiBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Automobili");
                });

            modelBuilder.Entity("Models.Ekspozitura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Grad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Ekspoziture");
                });

            modelBuilder.Entity("Models.Iznajmljivanja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AutoID")
                        .HasColumnType("int");

                    b.Property<int>("BrojDana")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIznajmljivanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EkspozituraID")
                        .HasColumnType("int");

                    b.Property<int?>("KlijentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AutoID");

                    b.HasIndex("EkspozituraID");

                    b.HasIndex("KlijentID");

                    b.ToTable("AutoEkspozitureKlijenti");
                });

            modelBuilder.Entity("Models.Klijent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BrojLicneKarte")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Klijenti");
                });

            modelBuilder.Entity("Models.Iznajmljivanja", b =>
                {
                    b.HasOne("Models.Auto", "Auto")
                        .WithMany("Iznajmljivanje")
                        .HasForeignKey("AutoID");

                    b.HasOne("Models.Ekspozitura", "Ekspozitura")
                        .WithMany("Iznajmljivanje")
                        .HasForeignKey("EkspozituraID");

                    b.HasOne("Models.Klijent", "Klijent")
                        .WithMany("Iznajmljivanje")
                        .HasForeignKey("KlijentID");

                    b.Navigation("Auto");

                    b.Navigation("Ekspozitura");

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("Models.Auto", b =>
                {
                    b.Navigation("Iznajmljivanje");
                });

            modelBuilder.Entity("Models.Ekspozitura", b =>
                {
                    b.Navigation("Iznajmljivanje");
                });

            modelBuilder.Entity("Models.Klijent", b =>
                {
                    b.Navigation("Iznajmljivanje");
                });
#pragma warning restore 612, 618
        }
    }
}
